import { defineConfig, type Plugin } from 'vite';

/**
 * What is copied out of `public/` and never passes through the bundle.
 *
 * Listed by hand, which is safe here and not safe for the built assets: these
 * names are ours and stable, where Vite hashes everything it emits. Reading
 * the directory instead would want `@types/node`, which the project does not
 * have and does not otherwise need.
 */
const PUBLIC_FILES = [
  './manifest.webmanifest',
  './icon-192.png',
  './icon-512.png',
  './icon-maskable-512.png',
];

/**
 * Emit a service worker that precaches whatever the build actually produced
 * (#98).
 *
 * Written here rather than pulled in as a plugin dependency, because the whole
 * job is "list the files and cache them" and a dependency for that is a
 * dependency to keep up to date. The list has to be generated: Vite hashes the
 * filenames, so a hand-written one is stale the first time anything changes.
 *
 * The strategy is deliberately plain. Everything in the build is precached on
 * install, and every request is served from the cache with the network as the
 * fallback. This is a game made of static files with no backend and no live
 * data: there is nothing that can go stale except the game itself, and a new
 * build gets a new cache name and takes over on the next visit.
 */
function serviceWorker(): Plugin {
  return {
    name: 'crosstown-service-worker',
    apply: 'build',
    // After the HTML plugin, or `index.html` is not in the bundle yet and the
    // one thing a player always asks for is the one thing not precached.
    enforce: 'post',
    generateBundle(_options, bundle) {
      // Everything the build produced, plus the static files copied out of
      // `public/`. `./` is the navigation request and is not the same cache
      // entry as `./index.html`, so both are listed.
      const files = [
        './',
        ...Object.keys(bundle).map((name) => `./${name}`),
        ...PUBLIC_FILES,
      ];
      // Named after the contents, so a build that changed nothing does not
      // evict a cache that is already correct, and one that did takes over.
      const version = hash(files.join('|'));

      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: workerSource(version, files),
      });
    },
  };
}

/** A short, stable digest of a string. Not a security hash; a cache name. */
function hash(text: string): string {
  let value = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    value ^= text.charCodeAt(i);
    value = Math.imul(value, 0x01000193) >>> 0;
  }
  return value.toString(36);
}

function workerSource(version: string, files: string[]): string {
  return `// Generated by vite.config.ts. Do not edit: it is rewritten every build.
const CACHE = 'crosstown-${version}';
const FILES = ${JSON.stringify(files, null, 2)};

self.addEventListener('install', (event) => {
  // Take over straight away rather than waiting for every tab to close: this
  // is a single-page game, and a player who reloads expects the new build.
  self.skipWaiting();
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(FILES)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    caches.match(event.request).then((hit) => {
      if (hit) return hit;
      // A navigation with a query string - \`?renderer=drive\`, which is a link
      // the README hands out - is not the same cache entry as \`./\`, so a
      // bookmarked one would fail offline. Any navigation falls back to the
      // page itself; the query string is read from \`location\` afterwards.
      if (event.request.mode === 'navigate') {
        return caches.match('./index.html').then((page) => page || fetch(event.request));
      }
      return fetch(event.request);
    }),
  );
});
`;
}

// base: './' keeps asset URLs relative so the built site works from any
// subpath (e.g. GitHub Pages) without extra config.
export default defineConfig({
  base: './',
  server: { open: false },
  plugins: [serviceWorker()],
});
