// Generated by `npm run propsync` from docs/downtown-props-edited.json - do not edit by hand.
// Place props in the Downtown Props editor (`npm run propexport -- --place downtown`), save,
// read the save back into docs/downtown-props-edited.json, and run the sync again.
//
// Nothing placed yet (#268).
import type { AuthoredProp } from './types';

/** Downtown's buildings and set dressing, in metres, as placed in the editor (#268). */
export const DOWNTOWN_PROPS: AuthoredProp[] = [];
