/**
 * Kestrel Bay's interstate loop, drawn rather than computed (#261).
 *
 * The same move as `roads.ts`, one level up: `interstate.ts` used to walk
 * four sides inset from the land's own bounding rectangle - a ring around
 * the middle of the city, which is why every ramp landed downtown and the
 * freeway read as a faster way round the same blocks rather than a journey
 * out and back. This is a hand-drawn route instead, checked against the real
 * grade and water rules the whole way with `tools/freewayexport.mjs` and the
 * editor it feeds.
 *
 * `FREEWAY_TUNNELS` are anchors, not full spans: a world position near where
 * each dive should start, resolved to the exact point on the loop nearest it.
 * Two are authored for their own reasons rather than found by the elevation
 * or water search - a tunnel under downtown, and one through the strait
 * north of the docks channel - and built unconditionally for it (#261's own
 * addInterstate doc comment says why). The other two were found by that
 * search and kept because they were good finds: the highest ground the loop
 * crosses on its western and northern stretches.
 *
 * Points are **world metres**, laid out as x,z pairs, against the frozen
 * landmass (`CITY_LAND_STREAM`) - the same convention `roads.ts` and
 * `plan.ts` use, for the same reason: a loop pinned to a coastline that
 * moved would mean nothing.
 *
 * Do not edit this file by hand. It is written by `npm run freewaysync` from
 * `docs/freeway-edited.json`, which is what the freeway loop editor saves.
 * Editing here instead means the next sync silently reverts you.
 *
 * 26 points · 15.0 km · 4 tunnel anchors
 */
import { UNITS_PER_METRE } from '../constants';
import type { Vec2 } from './types';

const points = (flat: number[]): Vec2[] => {
  const out: Vec2[] = [];
  for (let i = 0; i < flat.length; i += 2) {
    out.push({ x: flat[i] * UNITS_PER_METRE, z: flat[i + 1] * UNITS_PER_METRE });
  }
  return out;
};

export const FREEWAY_LOOP: Vec2[] = points([
    100, -2650, 1250, -2950, 1473, -2867, 2150, -2650, 2500, -1700, 2450, 250, 2108, 998, 1807,
    1515, 1553, 1882, 1280, 2588, 856, 2720, 292, 2579, -94, 2268, -301, 1769, -452, 1365, -555,
    922, -517, 445, -670, 76, -784, -199, -950, -600, -980, -943, -1026, -1459, -921, -1995,
    -847, -2221, -640, -2385, -362, -2408,
]);

export const FREEWAY_TUNNELS: Vec2[] = points([
    100, -2650, 1975, 1226, -478, 1254, 777, 2700,
]);
