// Generated by `npm run propsync` from docs/highmoor-props-edited.json - do not edit by hand.
// Place props in the Highmoor Park Props editor (`npm run propexport -- --place highmoor`), save,
// read the save back into docs/highmoor-props-edited.json, and run the sync again.
//
// Seed 0x4b657374, saved 2026-09-30T00:00:00.000Z.
import type { AuthoredProp } from './types';

/** Highmoor Park's set dressing, in metres, as placed in the editor (#460). */
export const HIGHMOOR_PROPS: AuthoredProp[] = [
  { kind: 'picnic-table', x: 1318, z: -70, angle: 0.4, note: 'The picnic area on the meadow' },
  { kind: 'picnic-table', x: 1332, z: -82, angle: 1.1 },
  { kind: 'picnic-table', x: 1306, z: -88, angle: -0.3 },
  { kind: 'picnic-table', x: 1322, z: -100, angle: 0.8 },
  { kind: 'picnic-table', x: 1296, z: -66, angle: 1.5 },
  { kind: 'picnic-table', x: 1340, z: -62, angle: -0.9 },
  { kind: 'bench', x: 1300, z: -110, angle: 0.2 },
  { kind: 'bench', x: 1346, z: -104, angle: -0.6 },
  { kind: 'bench', x: 1460.2, z: -55.8, angle: 0.785, note: 'The viewpoint, looking east' },
  { kind: 'bench', x: 1465.8, z: -50.2, angle: 0.785 },
  { kind: 'telescope', x: 1466.5, z: -56.5, angle: 2.356 },
  { kind: 'jump', x: 845, z: -550, angle: -1.052, variant: 'grass mound', note: 'The Descent\'s jump, off the west slope' },
];
