// Generated by `npm run propsync` from docs/industrial-props-edited.json - do not edit by hand.
// Place props in the Industrial Props editor (`npm run propexport -- --place industrial`), save,
// read the save back into docs/industrial-props-edited.json, and run the sync again.
//
// Nothing placed yet (#489).
import type { AuthoredProp } from './types';

/** Industrial's works, in metres, as placed in the editor (#489). */
export const INDUSTRIAL_PROPS: AuthoredProp[] = [];
