// Generated by `npm run propsync` from docs/midtown-south-props-edited.json - do not edit by hand.
// Place props in the Midtown south Props editor (`npm run propexport -- --place midtown-south`), save,
// read the save back into docs/midtown-south-props-edited.json, and run the sync again.
//
// Nothing placed yet (#487).
import type { AuthoredProp } from './types';

/** Midtown south's set dressing, in metres, as placed in the editor (#487). */
export const MIDTOWN_SOUTH_PROPS: AuthoredProp[] = [];
