// Generated by `npm run propsync` from docs/midtown-sw-props-edited.json - do not edit by hand.
// Place props in the Midtown south-west Props editor (`npm run propexport -- --place midtown-sw`), save,
// read the save back into docs/midtown-sw-props-edited.json, and run the sync again.
//
// Nothing placed yet (#488).
import type { AuthoredProp } from './types';

/** Midtown south-west's set dressing, in metres, as placed in the editor (#488). */
export const MIDTOWN_SW_PROPS: AuthoredProp[] = [];
