// Generated by `npm run propsync` from docs/tidewater-props-edited.json - do not edit by hand.
// Place props in the Tidewater Park Props editor (`npm run propexport -- --place tidewater`), save,
// read the save back into docs/tidewater-props-edited.json, and run the sync again.
//
// Seed 0x4b657374, saved 2026-09-30T00:00:00.000Z.
import type { AuthoredProp } from './types';

/** Tidewater Park's set dressing, in metres, as placed in the editor (#461). */
export const TIDEWATER_PROPS: AuthoredProp[] = [
  { kind: 'cafe', x: 310, z: -2600, angle: 1.571, note: 'The café, looking over the big pond' },
  { kind: 'toilet-block', x: 268, z: -2582, angle: 1.571 },
  { kind: 'bandstand', x: 300, z: -2705, angle: 0, note: 'The bandstand on the west lawn' },
  { kind: 'bench', x: 445.4, z: -2598, angle: -0.524, note: 'Round the big pond' },
  { kind: 'bench', x: 378.9, z: -2567, angle: -1.745 },
  { kind: 'bench', x: 329.9, z: -2651.9, angle: -3.491 },
  { kind: 'bench', x: 368.1, z: -2690.1, angle: -4.363 },
  { kind: 'bench', x: 422, z: -2685.4, angle: -5.236 },
  { kind: 'bench', x: 450.1, z: -2651.9, angle: -5.934 },
  { kind: 'bench', x: 863, z: -2760, angle: 0, note: 'Round the pond in the east loop' },
  { kind: 'bench', x: 810, z: -2707, angle: -1.571 },
  { kind: 'bench', x: 757, z: -2760, angle: -3.142 },
  { kind: 'bench', x: 810, z: -2813, angle: -4.712 },
];
