// Generated by `npm run propsync` from docs/wharf-props-edited.json - do not edit by hand.
// Place props in the Sablet Wharf Props editor (`npm run propexport -- --place docks`), save,
// read the save back into docs/wharf-props-edited.json, and run the sync again.
//
// Seed 0x4b657374, saved 2026-09-30T12:00:00.000Z.
import type { AuthoredProp } from './types';

/** Sablet Wharf's set dressing, in metres, as placed in the editor (#410). */
export const WHARF_PROPS: AuthoredProp[] = [
  { kind: 'jump', x: -1359.8, z: -2286.4, angle: 1.832, variant: 'built ramp', note: 'Pier jump - off the end of the jetty, 110 m of water to the east bank; wants about 240 km/h, which the straight across the wharf gives' },
];
