// Turn the drawn freeway loop into the generator's input.
//
// The same move as `roadsync.mjs`, one level up: the loop came out of the
// editor as a closed polyline plus a handful of tunnel anchors, checked
// against the real grade and water rules along the way (#261), and this is
// the step that makes `generate.ts` actually build it instead of the
// rectangle `draftLoop` stands in with.
//
// Usage:
//   npm run freewaysync                          # docs/freeway-edited.json -> src/game/city/freeway.ts
import { readFileSync, writeFileSync } from 'node:fs';

const source = process.argv[2] ?? 'docs/freeway-edited.json';
const out = 'src/game/city/freeway.ts';
const raw = JSON.parse(readFileSync(source, 'utf8'));

const path = raw.path ?? [];
const tunnels = raw.tunnels ?? [];

const perimeter = (() => {
  let d = 0;
  for (let i = 0; i < path.length; i++) {
    const a = path[i];
    const b = path[(i + 1) % path.length];
    d += Math.hypot(b[0] - a[0], b[1] - a[1]);
  }
  return d;
})();

// A flat x,z,x,z,... array, the same convention roads.ts writes points in:
// pairs are a reader's convention over it, not the array's own shape.
const flat = (points) => {
  const nums = points.flatMap(([x, z]) => [x, z]);
  const lines = [];
  let line = '   ';
  for (const n of nums) {
    const piece = `${n},`;
    if (line.length + piece.length + 1 > 96) {
      lines.push(line);
      line = '   ';
    }
    line += ` ${piece}`;
  }
  lines.push(line);
  return lines.join('\n');
};

const file = `/**
 * Kestrel Bay's interstate loop, drawn rather than computed (#261).
 *
 * The same move as \`roads.ts\`, one level up: \`interstate.ts\` used to walk
 * four sides inset from the land's own bounding rectangle - a ring around
 * the middle of the city, which is why every ramp landed downtown and the
 * freeway read as a faster way round the same blocks rather than a journey
 * out and back. This is a hand-drawn route instead, checked against the real
 * grade and water rules the whole way with \`tools/freewayexport.mjs\` and the
 * editor it feeds.
 *
 * \`FREEWAY_TUNNELS\` are anchors, not full spans: a world position near where
 * each dive should start, resolved to the exact point on the loop nearest it.
 * Two are authored for their own reasons rather than found by the elevation
 * or water search - a tunnel under downtown, and one through the strait
 * north of the docks channel - and built unconditionally for it (#261's own
 * addInterstate doc comment says why). The other two were found by that
 * search and kept because they were good finds: the highest ground the loop
 * crosses on its western and northern stretches.
 *
 * Points are **world metres**, laid out as x,z pairs, against the frozen
 * landmass (\`CITY_LAND_STREAM\`) - the same convention \`roads.ts\` and
 * \`plan.ts\` use, for the same reason: a loop pinned to a coastline that
 * moved would mean nothing.
 *
 * Do not edit this file by hand. It is written by \`npm run freewaysync\` from
 * \`docs/freeway-edited.json\`, which is what the freeway loop editor saves.
 * Editing here instead means the next sync silently reverts you.
 *
 * ${path.length} points · ${(perimeter / 1000).toFixed(1)} km · ${tunnels.length} tunnel anchors
 */
import { UNITS_PER_METRE } from '../constants';
import type { Vec2 } from './types';

const points = (flat: number[]): Vec2[] => {
  const out: Vec2[] = [];
  for (let i = 0; i < flat.length; i += 2) {
    out.push({ x: flat[i] * UNITS_PER_METRE, z: flat[i + 1] * UNITS_PER_METRE });
  }
  return out;
};

export const FREEWAY_LOOP: Vec2[] = points([
${flat(path)}
]);

export const FREEWAY_TUNNELS: Vec2[] = points([
${flat(tunnels)}
]);
`;

writeFileSync(out, file);
console.log(
  `wrote ${out}  ·  ${path.length} points  ·  ${(perimeter / 1000).toFixed(1)} km  ·  ` +
    `${tunnels.length} tunnel anchors  ·  ${(file.length / 1024).toFixed(0)} KB`,
);
