// Turn the prop editor's placements into the generator's input.
//
// The same loop the roads and the freeway closed: placed by hand in the
// editor (`npm run propexport`), saved to the page's store, read back into
// `docs/props-edited.json`, and written from there into a module the
// generator imports. The JSON is the record of what somebody decided; the
// module is that record in the shape the generator wants it.
//
// Metres, not world units, like `roads.ts` and `freeway.ts`: this file is read
// by people comparing it to the editor, and the editor speaks metres.
//
// Usage:
//   npm run propsync                        # docs/props-edited.json -> src/game/city/marrowprops.ts
import { readFileSync, writeFileSync } from 'node:fs';

const source = process.argv[2] ?? 'docs/props-edited.json';
const out = 'src/game/city/marrowprops.ts';
const raw = JSON.parse(readFileSync(source, 'utf8'));
// The store hands back the document; accept it bare or under a wrapper.
const doc = raw.props ? raw : raw.data ?? raw;
const props = doc.props ?? [];
if (props.length === 0) {
  console.error(`no props in ${source}`);
  process.exit(1);
}

const KINDS = [
  'gate', 'stack', 'plane-belly', 'plane-nose', 'fuselage', 'fuselage-hung', 'helicopter',
  'silo', 'water-tower', 'crane', 'mast', 'bunker', 'blast-wall', 'shed', 'cone', 'tree', 'jump', 'billboard',
];
const unknown = props.filter((p) => !KINDS.includes(p.kind));
if (unknown.length) {
  console.error(`unknown kinds: ${[...new Set(unknown.map((p) => p.kind))].join(', ')}`);
  process.exit(1);
}

const num = (v) => String(Math.round(v * 1000) / 1000);
const str = (v) => `'${String(v).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const lines = props.map((p) => {
  const parts = [`kind: ${str(p.kind)}`, `x: ${num(p.x)}`, `z: ${num(p.z)}`, `angle: ${num(p.angle)}`];
  if (p.w != null) parts.push(`w: ${num(p.w)}`);
  if (p.variant) parts.push(`variant: ${str(p.variant)}`);
  if (p.note) parts.push(`note: ${str(p.note)}`);
  return `  { ${parts.join(', ')} },`;
});

const body = `// Generated by \`npm run propsync\` from ${source} - do not edit by hand.
// Place props in the Marrow Field Props editor (\`npm run propexport\`), save,
// read the save back into ${source}, and run the sync again.
//
// Seed ${doc.seed}, saved ${doc.savedAt ?? 'at an unknown time'}.
import type { AuthoredProp } from './types';

/** Marrow Field's set dressing, in metres, as placed in the editor (#295). */
export const MARROW_PROPS: AuthoredProp[] = [
${lines.join('\n')}
];
`;
writeFileSync(out, body);
const count = {};
for (const p of props) count[p.kind] = (count[p.kind] ?? 0) + 1;
console.log(
  `wrote ${out}  ·  ${props.length} props  ·  ` +
    Object.entries(count)
      .map(([k, n]) => `${n} ${k}`)
      .join(', '),
);
